// Auto-generated by scripts/generateRegistry.ts — do not edit manually
import type { RegisteredGameComponent } from '@/lib/registeredGameComponent'
import PaiGow from '@/components/games/pai-gow/PaiGowGame'
import ExampleGame from '@/components/games/example-game/ExampleGame'
import FoxyShooter from '@/components/games/foxy-shooter/FoxyShooter'
import AxeRoulette from '@/components/games/axe-roulette/AxeRoulette'
import StreetLooker from '@/components/games/street-looker/StreetLooker'
import ChickenCrossing from '@/components/games/chicken-crossing/ChickenCrossing'
import LootTumble from '@/components/games/loot-tumble/LootTumble'
import CrashOrCashOut from '@/components/games/crash-or-cash-out/MyGame'
import MinefieldPath from '@/components/games/minefield-path/MyGame'
import DeadDraw from '@/components/games/dead-draw/DeadDraw'

const gameRegistry: Record<string, RegisteredGameComponent> = {
  'pai-gow': PaiGow,
  'example-game': ExampleGame,
  'foxy-shooter': FoxyShooter,
  'axe-roulette': AxeRoulette,
  'street-looker': StreetLooker,
  'chicken-crossing': ChickenCrossing,
  'loot-tumble': LootTumble,
  'crash-or-cash-out': CrashOrCashOut,
  'minefield-path': MinefieldPath,
  'dead-draw': DeadDraw,
}

export { gameRegistry }
