// Auto-generated by scripts/generateRegistry.ts — do not edit manually
import { ComponentType } from 'react'
import ExampleGame from '@/components/games/example-game/ExampleGame'

const gameRegistry: Record<string, ComponentType> = {
  'example-game': ExampleGame,
}

export { gameRegistry }
