/**
 * generateRegistry.ts
 *
 * Prebuild script that auto-generates lib/gameRegistry.ts by scanning
 * submissions/[partner]/[game]/metadata.json files.
 *
 * Runs automatically via the "prebuild" npm script before every build.
 * Do NOT edit lib/gameRegistry.ts by hand — it is overwritten on every build.
 */

import fs from 'fs'
import path from 'path'

interface GameMetadata {
  gameName: string
  mainComponent: string
  status: string
}

const SUBMISSIONS_DIR = path.join(process.cwd(), 'submissions')
const OUTPUT_PATH = path.join(process.cwd(), 'lib', 'gameRegistry.ts')

function discoverGames(): GameMetadata[] {
  const games: GameMetadata[] = []

  if (!fs.existsSync(SUBMISSIONS_DIR)) {
    console.warn('⚠️  No submissions/ directory found.')
    return games
  }

  const partners = fs.readdirSync(SUBMISSIONS_DIR)

  for (const partner of partners) {
    const partnerDir = path.join(SUBMISSIONS_DIR, partner)
    if (!fs.statSync(partnerDir).isDirectory()) continue

    const gameFolders = fs.readdirSync(partnerDir)

    for (const gameFolder of gameFolders) {
      const metadataPath = path.join(partnerDir, gameFolder, 'metadata.json')
      if (!fs.existsSync(metadataPath)) continue

      try {
        const raw = fs.readFileSync(metadataPath, 'utf-8')
        const metadata = JSON.parse(raw) as GameMetadata

        if (!metadata.gameName || !metadata.mainComponent) {
          console.warn(`⚠️  Skipping ${gameFolder} — missing gameName or mainComponent`)
          continue
        }

        // Verify the component directory actually exists
        const componentDir = path.join(process.cwd(), 'components', 'games', metadata.gameName)
        if (!fs.existsSync(componentDir)) {
          console.warn(`⚠️  Skipping ${metadata.gameName} — components/games/${metadata.gameName}/ not found`)
          continue
        }

        games.push(metadata)
        console.log(`  ✅ ${metadata.gameName} [${metadata.status}]`)
      } catch (err) {
        console.error(`  ❌ Failed to parse metadata.json for ${gameFolder}:`, err)
      }
    }
  }

  return games
}

function toPascalCase(kebab: string): string {
  return kebab
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
}

function generateRegistry(games: GameMetadata[]): string {
  if (games.length === 0) {
    return `// Auto-generated by scripts/generateRegistry.ts — do not edit manually
import { ComponentType } from 'react'

const gameRegistry: Record<string, ComponentType> = {}

export { gameRegistry }
`
  }

  const imports = games
    .map(({ gameName, mainComponent }) => {
      const modulePath = mainComponent.replace(/\.tsx$/, '')
      const alias = toPascalCase(gameName)
      return `import ${alias} from '@/components/games/${gameName}/${modulePath}'`
    })
    .join('\n')

  const entries = games
    .map(({ gameName }) => {
      const alias = toPascalCase(gameName)
      return `  '${gameName}': ${alias},`
    })
    .join('\n')

  return `// Auto-generated by scripts/generateRegistry.ts — do not edit manually
import { ComponentType } from 'react'
${imports}

const gameRegistry: Record<string, ComponentType> = {
${entries}
}

export { gameRegistry }
`
}

function main() {
  console.log('\n🔧 Generating gameRegistry.ts...\n')

  const games = discoverGames()
  const output = generateRegistry(games)

  fs.writeFileSync(OUTPUT_PATH, output, 'utf-8')

  console.log(`\n✅ gameRegistry.ts written with ${games.length} game(s).\n`)
}

main()
